### PR TITLE
Make blender icon more faithful to actual blender logo

### PR DESCRIPTION
**Pull request by gandalf3**
The current blender icon fails to pass [Blender's style guide](https://www.blender.org/about/logo/), with severe shape deformations.
The breeze guidelines [suggest avoiding significant alterations to application icons in order to respect trademarks](https://community.kde.org/KDE_Visual_Design_Group/HIG/IconDesign).
Plus, as a blender user, I feel the current icon just looks "wrong". Being used the official blender logo, this one feels top-heavy and out of proportion (most notably, the backwards tilt is missing and the arms are all the same length).

This PR makes the blender icon much closer to the original by following the original's shape much more closely. In addition, the main gradient is tweaked to follow the breeze convention of putting the lighter color on top.

### CODE REVIEW

**Comment by alexl-kde** [comment]
Thanks for your work.
It seems Blender guidelines are for internal usage and Breeze guidelines are intended as "respect the copyright laws".
I don't see your change as needed but I like it and it seems an improvement for me.
The maintainer will decide.

P.S. GitHub is not our preferred way for PRs, you should contribute as described in the README file, thanks.

**Comment by jensreu** [comment]
Just as a sidenote the guidelines refer as a reminder to avoid getting into legal trouble, not as a cut-and-dry rule. IE take for example Chrome, we know that we can get into legal issues if we mess around too much with it, KDE is large enough to be dragged to court but small enough to not be able to pay even the initial legal fee's. Hence the suggestion in the guidelines.

Now that doesn't say your suggestion isn't good, or should be rejected. Just a clarification on the issue with the guidelines.

Usability wise I am sure you would agree that our icon is unmistakably "Blender" and nothing else? (which should be credited to the designer of the Blender logo and not us, its very well done as it is a symbol instead of "a little picture" making it extremely recognizable).

But from there on in we have aesthetic and preference. And that is very very fiddly - that said though your icon is very well done and I don't think we can easily wave it away. ;) 

If you want, I think Alexl-kde and Andreas Kainz both would love to have you on board, you clearly have an eye for this. (this is the telegram group they use https://telegram.me/breezeicons but you can also find them on the #kde-vdg IRC group).

**Comment by alexl-kde** [comment]
It would be really nice if you could join us in our official Telegram group:

https://telegram.me/breezeicons

**Comment by gandalf3** [comment]
I see, thanks for the clarification.

I don't wish to say the old version was in any way _bad_ taken on its own, just that I personally, being the pedantic type and accustomed to the official icon, found serious enough issue with the more.. "fiddly" bits to take action ;)

I haven't heard of telegram before, so I hope you understand if I have to see what it is before I rush off to join.
I'm in IRC though if that works

**Comment by DarkknightAK** [comment]
Hi,

I like your patch and the new icon is already submitted. Thanks for your work and if you like to support us, you are very welcome. As jens and alex wrote telegram would help if you want to discuss something. I'm only from time to time in irc, but it would be also no problem when you submitt via github. good work is always welcome ;-)

**Comment by gandalf3** [comment]
@DarkknightAK Thanks!
I just noticed that for some reason, my icon is rendering as partially inverted (!) when actually installed and viewed in practice.
examp217

Does anyone know why this might be?

**Comment by DarkknightAK** [comment]
update the app icon theme should work now.

**Pull request closed without merging**
