### PR TITLE
Add edit-extend and edit-trim icons

### PR DESCRIPTION
**Pull request by tesfabpel**
Hi,
I added these two new icons (16px)...
I think they're useful for CAD-like apps.

### CODE REVIEW

**Comment by KAMiKAZOW** [comment]
@tesfabpel The Github repo is just a mirror. Since I'm not a KDE artist myself, I'm not sure where to best contact them about this. Probably either https://forum.kde.org/viewforum.php?f=285 or https://mail.kde.org/mailman/listinfo/kde-artists

**Comment by DarkknightAK** [comment]
Hi @tesfabpel you are very welcome to contribute to kde, but it's not possible via github. If you want to have your icons in the breeze-icons repo, please send it to me andreas_k at abwesend.de there we can discuss

**Comment by Thaodan** [comment]
You can add your changes and make a review board request.

**Comment by tesfabpel** [comment]
I'm sorry for the delay, but I was a bit busy and then I forgot about it...
I've created the review board request now...

**Pull request closed without merging**
